let umaString = 'um texto';
console.log(umaString.charAt(6));
console.log(umaString[4]);
console.log(umaString.indexOf('o', 3));
console.log(umaString.lastIndexOf('m', 3));
console.log(umaString.length);
console.log(umaString.slice(3, 8));
console.log(umaString.split(' '));
console.log(umaString.toUpperCase());
console.log(umaString.toLowerCase());
